remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Kara Dean]
description: [I am a PhD Candidate at Michigan State University with experience in quantitative microbial risk assessment, persistence, and dose response modeling.]
