---
title: |
       | Kara Jane Dean, M.S.
subtitle: | 
          | <font size="3" >Michigan State University</font>
          | <font size="3" >Biosystems and Agricultural Engineering</font>
          | <font size="3" >524 S. Shaw Lane, Rm. 101 Farrall Hall</font>
          | <font size="3" >East Lansing, MI 48824</font>
          | <font size="3" >deankara@msu.edu</font>
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **EDUCATION**
________________________________________________________________________________
<!---------------------------- --------------------------------->    | <!-- -->  
------------------------------------------------------------------|------------:
**PhD Biosystems Engineering** | December 2022  
Dual Degree: PhD Environmental Science and Policy  | 
Michigan State University, East Lansing, MI, GPA: 4.00   |
Advisor: Jade Mitchell, Ph.D.  	|   
**MS Biosystems Engineering**  | May 2019   
Master’s Thesis: Risk Assessment Models to Support Management of Opportunistic Pathogens in Piped Water Systems   |
Michigan State University, East Lansing, MI, GPA: 4.00	 |
Advisor: Jade Mitchell, Ph.D.	 |
**BS Biosystems Engineering**      | May 2018  
Michigan State University, East Lansing, MI, GPA: 3.93	 |


## **RESEARCH EXPERIENCE** 
_______________________________________________________________________________
**Research Associate- QMRA IV Program Coordinator **

  - Directed the daily logistics of course coordination, collaborated with STEM education faculty to collect and analyze assessment and evaluation data, supported the content creation of research education materials and outputs including interactive online training and in-person team science workshops, managed the interface between the pedagogical and content experts and the learning technology research experts, and assisted in the development of novel research case studies used for project-based learning.
  
**National Science Foundation Graduate Research Fellow **

  - Described the fate of pathogens in surface waters with mathematical models, identified factors influencing key persistence behaviors, and applied the improved persistence knowledge within the quantitative microbial risk assessment framework to characterize risks associated with pathogens in surface water matrices.   
  
**MS Graduate Research Assistant **    

  - Right Sizing Tomorrow’s Water Systems for Efficiency, Sustainability, and Public Health: Integrated the chemical and microbial analyses of water sampling efforts to determine risks associated with opportunistic pathogens in drinking water systems.  
  
**Undergraduate Researcher**  

  -  Center for Advancing Microbial Risk Assessment (CAMRA): Used previous peer-reviewed dose response studies to produce dose response models to be used in future quantitative microbial risk assessments.   
  
  -  Citizen Science Study of Contaminant Exposures Related to Water Affordability in Detroit: Aided in the experimental design and interaction with the community to gather and interpret water sampling results. 
  
  -  Global Water Pathogens Project: Performed a literature review to identify and analyze the persistence of microorganisms in different matrices (freshwater, seawater, wastewater, etc.) and fit novel persistence models using R Statistical Programming Language.
  
  -  MSU Extension: Helped conduct an energy efficiency case study on Grand Valley Farm’s implementation of solar heating panels, LED lighting, and center-pivot irrigation     systems

## **AWARDS AND HONORS**
________________________________________________________________________________
 <!-- -->    | <!-- -->  
-------------------------------------------------------------------|------:
Fitch H. Beach Award Winner, Biosystems and Agricultural Engineering|2022  
Fitch H. Beach Award Nominee, College of Engineering                |2022  
Travel Award Winner, College of Agriculture and Natural Resources   |2022   
National Science Foundation Graduate Research Fellow Program|	2019  
Best Poster Award for the Health, Food Safety & Biomechanics Category, Michigan State University Engineering Graduate Research Symposium| 2019  
Recognition for Outstanding Research, 2nd Place, Michigan State University Engineering Graduate Research Symposium|	2018  
Michigan State University, Graduate School Research Enhancement Award|	2018  
Biosystems and Agricultural Engineering Service Award|	2018
Biosystems and Agricultural Engineering Undergraduate Fellowship Winner|	2017  
Michigan State University Scholar-Athlete Award, Swimming and Diving|	2017  
Michigan State University Alumni Distinguished Scholar|	2014  
Honors College Member|	2014-18  

## **TEACHING EXPERIENCE**
________________________________________________________________________________
<!-------------- ------------>    | <!-- -->  
------------------------------------------------------------|---------------:
**Graduate Teaching Assistant** | FS 2018, 2020, 2021  
BE 449- Human Health Risk- Formal lab instruction, grading, assisting students  | 
**QMRA IV (NIH #R25GM135058) Co-Instructor (~40 students)**  | Summer 2022    
Fate and Transport Modeling (45 minutes)   |
Cost Benefit Analysis and Decision Trees (90 minutes)  |
**Guest Lecturer (~30 students)**  | FS 2019    
BE 449- Human Health Risk- Probability and Statistical Distributions (30 minutes)   |  
BE 449- Human Health Risk- QMRA Methodology and Examples (45 minutes) |  
**Grader**      | FS 2019   
BE 449- Human Health Risk- Grading labs, homeworks, and exams	 |  
**Undergraduate Teaching Assistant**  | 2017-2018   
BE 334- Biosystems Engineering Lab   |  
BE 456- Electric Power and Control |  

## **CERTIFICATIONS** 
_______________________________________________________________________________
 
 -  Participant of the Quantitative Microbial Risk Assessment Interdisciplinary Instructional
Institute (QMRA III) 2018. National Institute of General Medical Sciences of the National Institutes of Health (NIH)-Award Number R25GM108593. July 9-19, 2018.
Columbus, Ohio, USA

 -  Engineer in Training-Passed NCEES Fundamentals of Engineering Exam, MI (2018)

## **PEER-REVIEWED PUBLICATIONS** 
_______________________________________________________________________________
  1. **Dean, K.** & Mitchell, J. 2022. Meta-analysis addressing the implications of model uncertainty in understanding the persistence of indicators and pathogens in natural surface waters. *Environmental Science & Technology, 56*(17). https://doi.org/10.1021/acs.est.1c07552
  2. **Dean, K.**, Coaster, N., Young, K.,  & Mitchell, J. 2022. Development of a dose-response model for Elizabethkingia spp. *Risk Analysis, Early View*. https://doi.org/10.1111/risa.14013
  3. **Dean, K.** & Mitchell, J. 2022. Identifying Water Quality and Environmental Factors that Influence Indicator and Pathogen Decay in Natural Surface Waters. *Water Research*. https://doi.org/10.1016/j.watres.2022.118051
  4. Kline, A., **Dean, K.**, Kossik, A.L., Harrison, J.C., Januch, J.D., Beck, N.K., Zhou, N.A., Shirai, J.H., Boyle, D.S., Mitchell, J., & Meschke, J.S. 2022. Persistence of poliovirus types 2 and 3 in waste-impacted water and sediment. *PLOS One, 17*. https://doi.org/10.1371/journal.pone.0262761
  5. **Dean, K.** & Mitchell, J. 2022. Exploring the Effects of Natural Stressors on Indicators and Pathogens in Surface Waters with Persistence Modeling. *Public Health and Water Conference & Wastewater Disease Surveillance Summit Conference Proceedings*, Cincinnati, Ohio, 21-24, March. Available at:
https://www.accesswater.org/?id=-10080808&fromsearch=true#iosfirsthighlight
  6. **Dean, K.**, Tamrakar, S., Huang, Y., Rose, J.B., and Mitchell, J. 2021. Modeling the dose response relationship of waterborne *Acanthamoeba*. *Risk Analysis, 41*(1). https://doi.org/10.1111/risa.13603
  7. Mitchell, J., **Dean, K.**, & Haas, C. 2020. Ebola Virus Dose Response Model for Aerosolized Exposures: Insights from Primate Data. *Risk Analysis, 40*(11): 2390-2398. https://doi.org/10.1111/risa.13551
  8. Julien, R., Dreelin, E., Whelton, A.J., Lee, J., Aw, T.G., **Dean, K.**, & Mitchell, J. 2020.
Knowledge gaps and risks associated with premise plumbing drinking water quality. *AWWA Water Science, 2*(3). https://doi.org/10.1002/aws2.1177
  9. **Dean, K.** and Mitchell, J. 2020. A dose response model for the inhalation route of exposure to *P.aeruginosa*. *Microbial Risk Analysis, 15*. https://doi.org/10.1016/j.mran.2020.100115
  10. **Dean, K.**, Wissler, A., Hernandez-Suarez, J.S., Nejadhashemi, A.P., & Mitchell, J. 2020.
Modeling the Persistence of Viruses in Untreated Groundwater. *Science of the Total
Environment, 717*(15). https://doi.org/10.1016/j.scitotenv.2019.134599
  11. **Dean, K.** and Mitchell, J. 2020. Reverse QMRA for *Pseudomonas aeruginosa* in Premise
Plumbing to Inform Risk Management. *Journal of Environmental Engineering, 146*(3). https://doi.org/10.1061/(ASCE)EE.1943-7870.0001641
  12. **Dean, K.**, Weir, M.H., and Mitchell, J. 2019. Development of a Dose-Response Model for
*Naegleria fowleri*. *Journal of Water and Health, 17*(1): 63-71. https://doi.org/10.2166/wh.2018.181


## **PRESENTATIONS** 
_______________________________________________________________________________
  1. **Dean, K.** & Mitchell, J. “A generalizable model for pathogen persistence in surface waters.” Society for Risk Analysis Annual Meeting, Tampa, FL. December 4-8, 2022. Oral. 
  2. **Dean, K.**, Curtis, K., Gonzalez, R., & Mitchell, J. “Considering pathogen persistence within surface water risk assessments.” Society for Risk Analysis Annual Meeting, Tampa, FL. December 4-8, 2022. Oral. 
  3. **Dean, K.** & Mitchell, J. “What you resist, will persist.” Great Lakes Beach Association Meeting, Muskegon, MI. October 31-November 2, 2022. Oral. 
  4. **Dean, K.** & Mitchell, J. “The impact of persistence model selectin on the assessment of human risks in surface waters.” UNC Water & Health Conference, University of North Carolina Chapel Hill, NC. October 24-28, 2022. Poster. 
  5. **Dean, K.** & Mitchell, J. “A meta-analysis evaluating the persistence of indicators and pathogens in surface waters.” Association of Environmental Engineering and Science Professors, St. Louis, Missouri, June 28-30, 2022. Oral. 
  6. **Dean, K.** & Mitchell, J. "A Hierarchical Analysis to Identify Pathogen Persistence Relationships in Surface Waters with Implications for Risk Assessment." Engineering Graduate Research Symposium, East Lansing, MI. April 14, 2022. Poster.
  7. **Dean, K.** & Mitchell, J. “Comparing Pathogen and Indicator Persistence in Surface Water to Inform Decision Makers.” Environmental Science and Policy Program Research Symposium, Virtual Platform, March 31, 2022. Oral.
  8. **Dean, K.** & Mitchell, J. “Exploring the Effects of Natural Stressors on Indicators and Pathogens in Surface Waters with Persistence Modeling.” Public Health and Water
Conference & Wastewater Disease Surveillance Summit, Cincinnati, Ohio, March 21-24, 2022. Oral.
  9. **Dean, K.** & Mitchell, J. “Addressing Model Uncertainty for the Persistence of Pathogens and Indicator Organisms in Surface Water Matrices.” 2021 Annual Meeting for the Society for Risk Analysis, Virtual Platform, December 5-9, 2021. Oral.
  10. **Dean, K.** & Mitchell, J. “Developing a Dose Response Model for *Ebolavirus*.” 2020 Annual Meeting for the Society for Risk Analysis, Virtual Platform. December 13-17, 2020. Oral.
  11. **Dean, K.**, Hamilton, K., Rasheduzzaman, M. Tolofari, D., Yang, Z., Bartrand, T., Gurian, P.L., Haas, C.N., Mitchell, J., and Singh, R. “Quantitative Microbial Risk Assessment for Opportunistic Premise Plumbing Pathogens: Challenges and Results from Three Case
Studies.” American Water Works Association Annual Conference and Exposition,
Denver, CO. June 9-12, 2019. Oral.
 12. **Dean, K.** and Mitchell, J. “Quantifying the Risk of *P. aeruginosa* in Premise Plumbing for Building Design and Maintenance.” Association of Environmental Engineering and Science Professors Research and Education Conference, Tempe, AR. May 14-16, 2019. Poster.
 13. **Dean, K.** and Mitchell, J. “Effect of Exposure Route on Threshold Levels of Concern for *P.aeruginosa* in Premise Plumbing Systems.” Engineering Graduate Research Symposium,
East Lansing, MI. March 21, 2019. Poster.
 14. **Dean, K.** and Mitchell, J. “Reverse QMRA for *Pseudomonas aeruginosa* in a showering event to inform monitoring levels.” 2018 Annual Meeting of the Society for Risk Analysis,
New Orleans, LA. December 2-6, 2018. Oral.
 15. **Dean, K.**, Tolofari, D., Hull, N. and Pierce-Walker, J. “Impacts of Showering Compliance Rates on the Risk of Infection from *Cryptosporidium* spp. in Swimming Pools.” 2018 Annual Meeting of the Society for Risk Analysis, New Orleans, LA. December 2-6, 2018. Poster.
 16. **Dean, K.** and Mitchell, J. “Parameter Estimation to Model Virus Persistence.” Inverse
Problems Symposium, Michigan State University, MI. June 3-5, 2018. Oral.
 17. **Dean, K.J.**, Julien, R. and Mitchell, J. “Assessment of Risks Associated with *Pseudomonas aeruginosa* in Low Flow Fixtures in a Residential Green Building.” UNC Water Microbiology Conference, University of North Carolina Chapel Hill, NC. May 22-24, 2018. Oral.
 18. **Dean, K.**, Julien, R. and Mitchell, J. “Declining Water Use and the Compounding
Effects of Green Building Design.” Engineering Graduate Research Symposium,
Michigan State University, MI. March 29, 2018. Poster.
 19. **Dean, K.**, Willis, E., and Mitchell, J. Persistence Modeling of MS2. University
Undergraduate Research and Arts Forum. Michigan State University, MI. April 2018. Poster.
 20. Mitchell, J.,  **Dean, K.**, Tamrakar, S., Huang, Y. and Rose, J. “Opportunistic pathogen dose-response models.” 2017 Annual Meeting of the Society for Risk Analysis Arlington, VA. December 2017. Oral.
 21. **Dean, K.** and Mitchell, J. “Are Indicator Bacteria Representative of Actual Health
Risk: A Seawater Assessment.” University Undergraduate Research and Arts Forum.
Michigan State University, MI. April 2017. Poster.
 22. **Dean, K.** and Mitchell, J. “Developing Dose Response Models for Opportunistic

## **PROFESSIONAL MEMBERSHIPS** 
_______________________________________________________________________________
<!-------------- ------------>    | <!-- -->  
-----------------------------------------------------------|---------------:
Society for Risk Analysis | 2018-Present  
Water Environment Federation  | 2022   
Association of Environmental Engineering and Science Professors  | 2022   
American Society of Agricultural and Biological Engineers | 2018 

## **PROFESSIONAL SERVICE** 
_______________________________________________________________________________
<!-------------- ------------>    | <!-- -->  
---------------------------------------------------------------|---------------:
Co-Mentor for the SROP Program | SS 2020, 2021
Peer-Reviewer for Risk Analysis, Water Science, npj Clean Water, and Water Research | 2020-Present
Graduate Student Advisory Group | 2018-Present
      -  Chair for '20-'21 term  |
      -  Vice Chair for '19-'20 term  |
      -  Secretary & Social Chair for '18-'19 term   |
Microbial Risk Analysis Specialty Group | 2020-Present
      -  Served as the Secretary (2023) |
      -  Served as the Graduate Student Representative (2022) |
Dose Response Specialty Group | 2019-Present
      -  Served as the Graduate Student Representative (2019) |
American Society of Agricultural and Biological Engineers Annual Intl. Meeting | 2018
      -  Volunteer responsible for organizing materials and aiding presenters |
Plumbing Safety Workshop, Purdue University, IN | 2017
      -  Aided in the workshop note-taking efforts and supported the organizational staff |


## **Mentoring** 
_______________________________________________________________________________
 <!-- --> | <!-------------- ------------>    | <!-- -->  
---|------------------------------------------------------|---------------:
1.|	Tyler Stump, Biosystems Engineering, MSU	| SS 2022-Present
2.|	Jack Kivi, Biosystems Engineering, MSU	| FS 2021-SS 2022
3.|	Stephanie Starr, Biosystems Engineering, MSU	| Summer 2020-SS 2022
4.|	Gustavo Garay-Rodriguez, Crops and Agro-Environmental Sciences, University of Puerto Rico (MSU SROP)	| Summer 2021
5.|	Natalie Coaster, Biosystems Engineering, MSU	| FS 2019-Summer 2020
6.|	Stephen Gonzalez, Biochemistry, California State University, Fullerton (MSU SROP)	| Summer 2020
7.|	Esha Jain, Biosystems Engineering, MSU	| FS 2017-SS 2020

